### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNChevronView#3]
Hi @LeoNatan ,

![2019-04-21_16-43-37](https://user-images.githubusercontent.com/1782450/56471608-c5331300-6454-11e9-95a2-13b596179a9b.png)

Thank You.

**Comment by LeoNatan** [comment]
Did you update the project with new Xcode recommendations?
Those are harmless. Feel free to submit a PR. The block should have `void` in the declaration. For the other two, the warning should be disabled in the project settings.

**Comment by iDevelopper** [comment]
Yes I know for void, I won't submit a PR for that!

For the other two, why do you think warning should be disabled instead of explicitly add self->?

**Comment by LeoNatan** [comment]
Because it's ugly.

**Comment by LeoNatan** [comment]
Anyway, I will close this issue. I will upgrade the project when I have time. This is a very low priority. Thanks
